"""add user_id to Book model

Revision ID: c48eb9b2109d
Revises: 38c6b30083d7
Create Date: 2025-03-24 18:26:23.227049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48eb9b2109d'
down_revision: Union[str, None] = '38c6b30083d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # 外部キー制約名は明示的に指定する方が望ましい (例: 'fk_books_user_id')
        # None のままでも動作するが、管理上推奨
        batch_op.create_foreign_key('fk_books_user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        # 外部キー制約名は upgrade で指定したものと同じにする
        batch_op.drop_constraint('fk_books_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
