"""Add cover_image_url to Book model

Revision ID: e7f75b9c84d2
Revises: c5e8d9f12345
Create Date: 2025-04-14 22:26:31.009135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f75b9c84d2'
down_revision: Union[str, None] = 'c5e8d9f12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('cover_image_url', sa.String(), nullable=True))
    op.drop_index('highlights_search_idx', table_name='highlights', postgresql_using='gin')
    op.drop_column('highlights', 'search_vector')
    op.create_index(op.f('ix_remix_id'), 'remix', ['id'], unique=False)
    op.add_column('search_history', sa.Column('result_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'result_count')
    op.drop_index(op.f('ix_remix_id'), table_name='remix')
    op.add_column('highlights', sa.Column('search_vector', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('highlights_search_idx', 'highlights', [sa.text("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.drop_column('books', 'cover_image_url')
    # ### end Alembic commands ###
